### ISSUE TITLE
[Bug] no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by jason-hwang** [growthbook/growthbook#1174]
### Summary
`docker-compose up` command is not working on `apple silicon(m1)`.

#### Expected Behavior

`docker-compose` should be run as well.

#### Current Behavior

`docker-compose` is not working with below message:
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

![image](https://user-images.githubusercontent.com/4724172/231529347-f32ccfc9-6b59-4d0b-8dfc-860fcf2db062.png)

**Comment by 0r0loo** [comment]
try yarn install

**Comment by 0r0loo** [comment]
try
```yaml
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    platform: linux/x86_64
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
    platform: linux/x86_64
volumes:
  uploads:

```
