### ISSUE TITLE
[Feature] Declarative bootstrapping / Organization configuration

### ISSUE THREAD

**Issue by BadLiveware** [growthbook/growthbook#1310]
### Description of Feature

We are presently in the process of implementing Growthbook and deploying it on Kubernetes. While the majority of the process is running smoothly, we've encountered a few challenges.

One of these pertains to bootstrapping Growthbook declaratively. While the issue has been partly addressed in the solution provided by #36, it seems there's no clear method (to the best of my knowledge) to configure the initial bootstrap of the organization declaratively. It would certainly be beneficial if we could establish a method to set up Growthbook entirely in a non-interactive manner.

An example:
```yaml
# organization.yml - Separate file so config.yml can be handled in a non-secret way
organization:
  name: xyz
  owner:
    name: admin
    email: admin@xyz.com
    password: zyx
```

### Related Issues

- #36
