### ISSUE TITLE
[Feature] Declarative API key for Growthbook proxy

### ISSUE THREAD

**Issue by BadLiveware** [growthbook/growthbook#1313]
### Description of Feature

We are presently in the process of implementing Growthbook and deploying it on Kubernetes. While the majority of the process is running smoothly, we've encountered a few challenges.

One of these pertains to bootstrapping Growthbook _proxy_ (and other apps) declaratively. The current solution requires us to manually interactively provision an API key in order to connect the proxy and api, it would be beneficial to be able to declaratively configure/provision these keys to avoid having a manual step to deploying a Growthbook solution.

An example:
```yaml
# api-keys.yml # Separate file to ease maintenence of public vs secret config
keys:
- name: proxy
  key: secret_gb_asdjakASLDjasdkalsdlkaskld
```

### Related Issues

- #36
- #1310
