### ISSUE TITLE
[Bug] Empty reply from API on port 3100 when using static IP and API_HOST and APP_ORIGIN variables

### ISSUE THREAD

**Issue by hbbtstar** [growthbook/growthbook#1968]
### Summary

When setting API_HOST and APP_ORIGIN in docker-compose.yml, the frontend at port 3000 is reachable but it (nor I) can reach the API at 3100. When I curl localhost:3100 (or the static IP that I specify in the yml file) I receive the following error:

```
ubuntu@ip-10-0-0-16:~/growthbook$ curl 127.0.0.1:3100
curl: (52) Empty reply from server
```

However, when I remove the static IP from the docker-compose.yml, the API endpoint behaves normally:

```
ubuntu@ip-10-0-0-16:~/growthbook$ curl localhost:3100
{
  "name": "GrowthBook API",
  "production": false,
  "api_host": "http://localhost:3100",
  "app_origin": "http://localhost:3000",
  "config_source": "db",
  "email_enabled": false,
  "build": {
    "sha": "ec88dce5a1983f2cfc47d9dba9b6f42fd37995cf",
    "date": "2023-12-18T11:42:30Z"
  }
```

I'm able to reproduce this issue locally as well, to rule out any AWS security shenanigans. The front-end appears unaffected and works fine- the only thing that does not work is the back-end Express server. 

#### Expected Behavior

When I set the API_HOST environment variable in docker-compose.yml to a static IP, the back-end responds to requests on that static IP URL.

#### Current Behavior

When I set the API_HOST environment variable in docker-compose.yml to a static IP, the back-end ceases to respond to requests.

#### Steps to Reproduce

1. clone and start growthbook docker image as described in the README.md.
2. Run `curl localhost:3100` and confirm that the API is reachable.
3. Change the API_HOST variable to `http://127.0.0.1:3100` (or any static IP) and restart the docker image
4. `curl 127.0.0.1:3100` (or `curl localhost:3100`) will both return Empty reply from server. 

I will provide both working and non-working ymls below if that helps!

#### Functional docker-compose.yml
```
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      # - APP_ORIGIN=http://54.237.33.211:3000
      # - API_HOST=http://54.237.33.211:3100
      - CORS_ORIGIN_REGEX='.*'
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
```

#### Non-Functional docker.compose.yml
```
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - APP_ORIGIN=http://54.237.33.211:3000
      - API_HOST=http://54.237.33.211:3100
      - CORS_ORIGIN_REGEX='.*'
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
```
