### ISSUE TITLE
[Bug] winston-transport package is missing for start:with-tracing

### ISSUE THREAD

**Issue by aurelijusbanelis** [growthbook/growthbook#2742]
### Summary

I was following [Open Telemetry](https://docs.growthbook.io/self-host/env#observability-opentelemetry) integration guide.
I wanted to integrate [NewRelic](https://docs.newrelic.com/docs/opentelemetry/best-practices/opentelemetry-otlp/).

Got errors in logs

#### Expected Behavior

No noise in logs.

Also, tracing context not lost in logs (e.g. `trace_id` part):
```jsonl
{"level":30,"time":1721051393548,"pid":58,"hostname":"814739bbcfeb","msg":"Deleted 0 old agenda jobs in 17ms"}
{"level":50,"time":1721051624733,"pid":58,"hostname":"814739bbcfeb","trace_id":"3867d78285dd382e981ca64be12f57f9","span_id":"53fca9c2aac24aa4","trace_flags":"01","msg":"getaddrinfo EAI_AGAIN mongo"}
```

#### Current Behavior

Missing module is logged:

```
@opentelemetry/instrumentation-winston OpenTelemetry Winston transport is not available, log records will not be automatically sent. Error: Cannot find module '@opentelemetry/winston-transport'
```

<details>
<summary>Full stack trace</summary>

```
@opentelemetry/instrumentation-winston OpenTelemetry Winston transport is not available, log records will not be automatically sent. Error: Cannot find module '@opentelemetry/winston-transport'
Require stack:
- /usr/local/src/app/node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js
- /usr/local/src/app/node_modules/@opentelemetry/instrumentation-winston/build/src/index.js
- /usr/local/src/app/node_modules/@opentelemetry/auto-instrumentations-node/build/src/utils.js
- /usr/local/src/app/node_modules/@opentelemetry/auto-instrumentations-node/build/src/index.js
- /usr/local/src/app/packages/back-end/dist/tracing.js
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at Hook._require.Module.require (/usr/local/src/app/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/helpers:130:18)
    at DerivedLogger.patchedConfigure (/usr/local/src/app/node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js:132:67)
    at new Logger (/usr/local/src/app/node_modules/winston/lib/winston/logger.js:42:10)
    at new DerivedLogger (/usr/local/src/app/node_modules/winston/lib/winston/create-logger.js:44:7)
    at module.exports [as createLogger] (/usr/local/src/app/node_modules/winston/lib/winston/create-logger.js:48:18)
    at Object.<anonymous> (/usr/local/src/app/node_modules/winston/lib/winston.js:89:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/src/app/node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js',
    '/usr/local/src/app/node_modules/@opentelemetry/instrumentation-winston/build/src/index.js',
    '/usr/local/src/app/node_modules/@opentelemetry/auto-instrumentations-node/build/src/utils.js',
    '/usr/local/src/app/node_modules/@opentelemetry/auto-instrumentations-node/build/src/index.js',
    '/usr/local/src/app/packages/back-end/dist/tracing.js',
    'internal/preload'
  ]
}
```

</details>

### How to reproduce

`docker-compose.yml`:

```yml
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - OTEL_SERVICE_NAME=Growthbook-Dev
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.eu01.nr-data.net
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=PLACEHOLDER_FOR_REAL_KEY
      - OTEL_NODE_RESOURCE_DETECTORS=none
    command:
      - "yarn"
      - "start:with-tracing"
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
```

Because `PLACEHOLDER_FOR_REAL_KEY` – `Error: PeriodicExportingMetricReader: metrics export failed (error OTLPExporterError: Unauthorized)` is expected.

### How to fix

I managed to not get error with `Dockerfile`:

```Dockerfile
FROM growthbook/growthbook:latest

RUN cd packages/back-end && yarn add @opentelemetry/winston-transport && cd -
```

I assume, dependency is missing in https://github.com/growthbook/growthbook/blob/main/packages/back-end/package.json)](https://github.com/growthbook/growthbook/blob/main/packages/back-end/package.json)

### How I tested patched version

I tested with locally build image:

```shell
docker build . -t growthbook/growthbook:local --no-cache
```

And then

```yml
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:local" # <-- testing patched version
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - OTEL_SERVICE_NAME=Growthbook-Dev
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.eu01.nr-data.net
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=PLACEHOLDER_FOR_REAL_KEY
      - OTEL_NODE_RESOURCE_DETECTORS=none
    command:
      - "yarn"
      - "start:with-tracing"
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
```

### Impact

Despite known workaround (patch), it should not be a hard task to patch `upstream`.

P.S. I am willing to create Pull request, if that would speed up fixing the issue.
