### ISSUE TITLE
[Bug] Logs are not forwarded through otlp

### ISSUE THREAD

**Issue by adomaskizogian** [growthbook/growthbook#2959]
### Summary

Log forwarding using otlp does not work. Other signals - traces and metrics - are forwarded and collected as expected.

### How to Reproduce

```yaml
#otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  debug/noop:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/noop]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

```yaml
# docker-compose.yml
version: "3"
services:
  otelcol:
    image: "otel/opentelemetry-collector-contrib:latest"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4318:4318 # OTLP http receiver
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db

  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
      - otelcol
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318/
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/json
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
    command:
      - yarn
      - start:with-tracing
volumes:
  uploads:
  mongodata:
```

run `docker compose up -d`. On the same terminal run `docker compose logs otelcol -f`, open another and run `docker compose logs growthbook -f`. Both terminals should be opened at the same dir where the docker-compse.yml is located.

Make growthbook to log something. For example `curl http://localhost:3000/features/404` or any other request for a not available page produces a long entry. Log entry on growthbook log watch will appear, will contain contextual attributes. Otelcol will not fire any LogsExporter info event. Otelcol does record info logs on MetricsExporter and TracesExproter.

#### Expected Behavior

Logs are forwarded using configured protocol.

#### Current Behavior

Logs appear on the stderr and have contextual attributes such as span id but are not observed on otel collector. Otel collector simply does not receive them.
Some logs are structured and logged in json. Some are semi-structured. Ensuring consistency if also really welcome.
