### ISSUE TITLE
Support running growthbook in codespace

### ISSUE THREAD

**Issue by wulfland** [growthbook/growthbook#296]
I've tried to run growthbook in a GitHub codespace - but I receive the following error after connecting to the port 300 after the `docker-compose up -d`:
<img width="320" alt="2022-03-25_10-51-46" src="https://user-images.githubusercontent.com/5276337/160097966-fb554c6a-d39c-4fe9-891d-138479939d33.png">
 
I guess this is because the port is not accessible using localhost:
<img width="1193" alt="2022-03-25_10-52-15" src="https://user-images.githubusercontent.com/5276337/160098067-f6e01c15-6bc5-4420-8a05-5effd593aad6.png">

Did anyone try this?

**Comment by jdorn** [comment]
https://docs.growthbook.io/self-host/config#domains-and-ports

There are 2 environment variables you need to set if you are using a different domain. `APP_ORIGIN` and `API_HOST`

**Comment by wulfland** [comment]
Set the variables in the docker-compose to the ports of codespaces and it works:

```yaml
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/
      - APP_ORIGIN=https://wulfland-growthbook-growthbook-g44xvpg4hvgwx-3000.githubpreview.dev
      - API_HOST=https://wulfland-growthbook-growthbook-g44xvpg4hvgwx-3100.githubpreview.dev
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
```

Thanks for the help.
