### ISSUE TITLE
[Bug] Issue with maxConcurrentQueries

### ISSUE THREAD

**Issue by itestyoy** [growthbook/growthbook#3291]
Hi!

It seems that `maxConcurrentQueries: 2` isn’t working correctly.
After the first 2 queries start, when one of them finishes, Growthbook runs the rest of the queries all at once.
For example, if we have 6 metrics, Growthbook runs 4 additional metrics as soon as one of the first 2 finishes.

```
datasources:
  warehouse:
    type: bigquery
    params:
      authType: auto
    name: A/B Tests
    settings:
      maxConcurrentQueries: 2
```

also we got `Query execution was interupted. Please try again.` but query is running in database 

Build: [3.3.0+4570688](https://github.com/growthbook/growthbook/commit/4570688c6781d5c642285f5b20799f3f9db3adfa) (2024-11-12)
