### ISSUE TITLE
Support configuration via code

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#36]
Currently, all organizations, datasources, metrics, dimensions, apikeys, webhooks, and settings are defined within MongoDB.

For self-hosted installations, we should support defining these (or a subset of these) via a configuration file.  Thinking of an initial yml structure like this:

```yml
organization:
  name: My Company
datasources:
  warehouse:
    name: Main Warehouse
    type: postgres
    host: localhost
    port: 5432
    user: root
    password: ${POSTGRES_PASSWORD}
    ...
metrics:
  signups:
    name: Sign Ups
    type: binomial
    datasource: warehouse
    sql: SELECT user_id, timestamp from signups
    ...
dimensions:
  country:
    name: Country
    datasource: warehouse
    sql: SELECT user_id, country as value from users
```

When the config file is present, the following should happen:
-  Load the config file on back-end startup and throw error immediately if the structure is invalid
-  The model classes for organizations, metrics, datasources, and dimensions will return data from config instead of mongo and throw an error when trying to edit or create
-  Signing up for an account in the UI will automatically add the person to the organization in the config
-  The front-end hides all CTAs to create or edit datasources, metrics, and dimensions
-  Any blank-slate page for datasources, metrics, or dimensions (e.g. onboarding) should show config instructions instead of a create button
