### ISSUE TITLE
Add aggregateFilter via API for FactMetric

### ISSUE THREAD

**Issue by itestyoy** [growthbook/growthbook#3783]
Hi! How to add `aggregateFilter` (User Filter) via API for FactMetric?

We tried this with bulk import, but it seems it didn’t work. 

Could you please add this possibility?

```yml
- id: level-completed-1-count
  data: 
   name: User with Completed 1 Level
   metricType: proportion
   numerator: 
    factTableId: user-datasource
    aggregateFilter: ">=1"
    aggregateFilterColumn: compleated
```

**Comment by itestyoy** [comment]
We tried this with bulk import, but it seems it didn’t work.

```yml
- id: level-completed-1-count
  data: 
   name: User with Completed 1 Level
   metricType: proportion
   numerator: 
    factTableId: user-datasource
    aggregateFilter: ">=1"
    aggregateFilterColumn: compleated
```
