### ISSUE TITLE
[Bug]: Running GB in Google Cloud with nginx, docker and SSL

### ISSUE THREAD

**Issue by Thorbenl** [growthbook/growthbook#641]
We would love to selfhost GB on Google Cloud, but have run into a little bit of trouble with SSL, and none SSL connections.
We have tried the following setup, running everything in docker:

```yaml
version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - growthbook
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:/etc/nginx/conf.d
      - /etc/ssl:/etc/nginx/ssl/
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - APP_ORIGIN="http://localhost:3000/"
      - API_HOST="http://localhost:3100/"
      - MONGODB_URI=mongodb://root:password@mongo:27017/
      - JWT_SECRET="ellojensishandsome"
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
```

And the nginx conf:
```
events { }

http {

  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

  server {
    listen 80;
    server_namecustom.domain.io;
    return 301 https://custom.domain.io$request_uri;
         }

   server {
    listen 443 ssl;
    server_name custom.domain.io;

    ssl_certificate /etc/nginx/ssl/gb.crt;
    ssl_certificate_key /etc/nginx/ssl/gb.key;

    access_log /var/log/nginx/data-access.log combined;

    location / {
       proxy_pass http://growthbook:3000/;
       proxy_set_header X-Real-IP  $remote_addr;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_redirect http://growthbook:3000/ $scheme://$http_host/;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;
       proxy_read_timeout 20d;
       proxy_buffering off;
       }
   }
}
```

Not sure how easy of a fix this is, but I think i am very close. I would love to get some hint on why this doesnt work.
We get the following error: 

![Screenshot 2022-10-17 at 15 17 25](https://user-images.githubusercontent.com/37654145/196187048-fe51fa01-4c54-415f-a35b-6e855182ee1a.jpg)
