### ISSUE TITLE
CROS Access not working [Bug] 

### ISSUE THREAD

**Issue by PrasanjitPattanaik** [growthbook/growthbook#777]
### Summary

CROS access is not working even after adding environment variables
environment:
    - APP_ORIGIN=http://<my ip>:3000
    - API_HOST=http://<my ip>:3100
I have added this line in docker-compose.yml file with my IP address but still it is not working. And it is pointing to localhost
#### Expected Behavior

After running docker-compose it is not reading the environment variables

**Comment by michtesar** [comment]
Hi, I am facing the same problem. This is my docker-compose component for growthbook:
```
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "4000:3000"
      - "4100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/
      - APP_ORIGIN=http:localhost:4000
      - API_HOST=http://localhost:4100
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
```
